# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: JaroslavSafar.BrowserGammaFix
PackageVersion: 0.7.2
MinimumOSVersion: 10.0.22000.0
Installers:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: Gamma22Tray/Gamma22Tray.exe
    PortableCommandAlias: BrowserGammaFix.exe
  InstallerUrl: https://github.com/mrsaliericz/browser-gamma-fix/releases/download/v0.7.2/BrowserGammaFix-win64.zip
  InstallerSha256: 2835A01AA156481C367D9C11B456C6BD1EAD7CE72C325C7583605B7C02796D6F
ManifestType: installer
ManifestVersion: 1.12.0
